export {default as Logo} from './Logo.svg'
export {default as LogoLight} from './LogoLight.svg'
export {default as NotFoundIcon} from './NotFoundIcon.svg'
export {default as MainLogo} from './MainLogo.svg'
export {default as LinkedinIcon} from './LinkedinIcon.svg'
export {default as GithubIcon} from './GithubIcon.svg'
