export { default as Logo } from "./Logo.svg"
export { default as LogoLight } from "./LogoLight.svg"
export { default as GithubIcon } from "./GithubIcon.svg"
export { default as GithubIconRed } from "./GithubIconRed.svg"
export { default as LinkedinIcon } from "./LinkedinIcon.svg"
export { default as LinkedinIconRed } from "./LinkedinIconRed.svg"
export { default as NotFoundIcon } from "./NotFoundIcon.svg"
